// Verbatim copy of cortana/clients/apple/Shared/Theme+Tokens.swift (GENERATED there from
// cortana/design/tokens.json). Refresh by copying; never edit here.
// GENERATED by cortana/scripts/design-tokens.ts from cortana/design/tokens.json. Do not edit by hand.
// Theme.swift is the public API (Theme.bg, .ink, .gold, fonts); this file is only the values.

import SwiftUI

/// The "Field" design tokens, v1. Colours are light/dark pairs that resolve per appearance.
enum DesignTokens {
    struct Pair: Equatable { let light: UInt32; let dark: UInt32 }

    enum Colors {
        static let bg            = Pair(light: 0xF6F7FC, dark: 0x0A0C18)   // window / page ground
        static let surface       = Pair(light: 0xFFFFFF, dark: 0x151834)   // cards, sheets, the user bubble in dark
        static let surface2      = Pair(light: 0xEDEFF9, dark: 0x1B1F42)   // raised or pressed surface; user bubble in light; code ground
        static let hairline      = Pair(light: 0xDFE2F0, dark: 0x232746)   // dividers and 1px card strokes; never text
        static let ink           = Pair(light: 0x12142A, dark: 0xE6E8F6)   // primary text
        static let muted         = Pair(light: 0x5E6285, dark: 0x8589B5)   // secondary text, meta, icons at rest (AA on bg and surface)
        static let faint         = Pair(light: 0xA3A7C2, dark: 0x4A4E74)   // placeholder, disabled, decorative only (fails AA on purpose: never for information)
        static let accent        = Pair(light: 0x4453C9, dark: 0x9DB0FF)   // periwinkle: the ONE active colour. Live state, the primary action, links
        static let accentBright  = Pair(light: 0x5B6BE0, dark: 0xC3D2FF)   // hover / pressed / emphasis of accent
        static let onAccent      = Pair(light: 0xFFFFFF, dark: 0x0A0C18)   // text and glyphs on an accent fill
        static let good          = Pair(light: 0x1E8452, dark: 0x4CC38A)   // ok, done, delivered
        static let warn          = Pair(light: 0x9A6200, dark: 0xE8B04B)   // attention, paused, blocked, over soft cap
        static let bad           = Pair(light: 0xC8283A, dark: 0xF2555A)   // failed, rejected, unreachable, destructive
        static let external      = Pair(light: 0x0F766E, dark: 0x2DD4BF)   // provenance: an answer from an external model or the web
        static let svcOpenrouter = Pair(light: 0x5B4FCF, dark: 0xA99BFF)   // chart series + cost card: OpenRouter (the SAME colour in the cards and the chart legend)
        static let svcElevenlabs = Pair(light: 0xBE185D, dark: 0xF472B6)   // chart series + cost card: ElevenLabs
        static let svcDeepgram   = Pair(light: 0x0E7490, dark: 0x22D3EE)   // chart series + cost card: Deepgram
        static let svcOther      = Pair(light: 0x6B7280, dark: 0x9CA3AF)   // chart series + cost card: any other service
        static let chart1        = Pair(light: 0x4453C9, dark: 0x7088F0)   // reply charts: series 1, in fixed order, never cycled (dataviz validator: all six checks pass on surface, both modes)
        static let chart2        = Pair(light: 0xE0662F, dark: 0xE0662F)   // reply charts: series 2
        static let chart3        = Pair(light: 0x17A374, dark: 0x17A374)   // reply charts: series 3
        static let chart4        = Pair(light: 0xC98500, dark: 0xC98500)   // reply charts: series 4
        static let chart5        = Pair(light: 0xD9558A, dark: 0xD9558A)   // reply charts: series 5
        static let chart6        = Pair(light: 0x8A5BD6, dark: 0x9478EC)   // reply charts: series 6. A 7th series folds into Other (svcOther), never a new hue
    }

    /// Spacing on a 4 pt grid.
    enum Space {
        static let xxs: CGFloat = 2
        static let xs: CGFloat = 4
        static let sm: CGFloat = 8
        static let md: CGFloat = 12
        static let lg: CGFloat = 16
        static let xl: CGFloat = 20
        static let xxl: CGFloat = 24
        static let x3: CGFloat = 32
        static let x4: CGFloat = 48
    }

    /// Corner radii. Nest concentrically: inner = outer - padding.
    enum Radius {
        static let xs: CGFloat = 6
        static let sm: CGFloat = 10
        static let md: CGFloat = 14
        static let lg: CGFloat = 20
        static let xl: CGFloat = 28
        static let pill: CGFloat = 999
    }

    enum Layout {
        static let readingWidth: CGFloat = 760
        static let composerMaxWidth: CGFloat = 760
        static let gutterPhone: CGFloat = 16
        static let gutterMac: CGFloat = 28
        static let sidebarMac: CGFloat = 220
        static let hitTarget: CGFloat = 44
        static let streamGutter: CGFloat = 20
        static let messageGap: CGFloat = 14
        static let bubblePadX: CGFloat = 14
        static let bubblePadY: CGFloat = 9
        static let bubbleRadius: CGFloat = 18
        static let bubbleInset: CGFloat = 76
        static let chatLineGap: CGFloat = 4
        static let separatorTop: CGFloat = 6
        static let filterBarHeight: CGFloat = 36
        static let fieldHeight: CGFloat = 40
        static let drawerWidth: CGFloat = 318
        static let drawerInset: CGFloat = 22
        static let drawerRowHeight: CGFloat = 44
        static let drawerSubInset: CGFloat = 56
        static let drawerGroupTop: CGFloat = 12
    }

    /// Seconds (spring response / damping fraction for the two spring values).
    enum Motion {
        static let quick: Double = 0.15
        static let standard: Double = 0.25
        static let slow: Double = 0.4
        static let springResponse: Double = 0.35
        static let springDamping: Double = 0.85
    }

    enum Glass {
        static let tintOpacityDark: Double = 0.72
        static let tintOpacityLight: Double = 0.55
    }

    /// Semantic text styles: the Dynamic Type style each role maps to, and its weight.
    enum TypeScale {
        static let display = Font.system(.title2).weight(.bold)
        static let title = Font.system(.title3).weight(.semibold)
        static let headline = Font.system(.headline).weight(.semibold)
        static let body = Font.system(.body).weight(.regular)
        static let callout = Font.system(.callout).weight(.regular)
        static let subhead = Font.system(.subheadline).weight(.regular)
        static let caption = Font.system(.caption).weight(.regular)
        static let micro = Font.system(.caption2).weight(.semibold)
        static let code = Font.system(.callout, design: .monospaced).weight(.regular)
    }
}
